name: Docker image Creation and Push to DockerHub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: The Main Build Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - uses: docker/setup-qemu-action@v3
        name: Setup Docker Qemu

      - uses: docker/setup-buildx-action@v3
        name: Setup Docker Buildx

      - uses: docker/login-action@v3
        name: Dockerhub Login
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - uses: docker/build-push-action@v3
        name: Build and Push
        with:
          push: true
          tag: ${{ secrets.USERNAME }}/SpringBootDockerGithubAction:latest